version: 0.1
phases:
  build:
    commands: 
    - apt-get update
    - apt-get -y install wget
    - apt-get -y install default-jdk
    - wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
    - mkdir zap
    - mkdir report
    - tar -xvf ZAP_2.11.1_Linux.tar.gz
    - cd ZAP_2.11.1
    - mkdir generated_report
    - ./zap.sh --help
    - ./zap.sh -cmd -quickurl https://ads.asmadiya.com -quickprogress -quickout generated_report/zap_report2.html 
artifacts:
  files:
     - "**/*"
  discard-paths: no
  base-directory: ZAP_2.11.1/generated_report

  #looking for the work
