---
version: 0.2

phases:
  install:
    commands:
      - wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-5.3.0-release.zip
      - unzip dependency-check-*
      - export PATH=dependency-check/bin:$PATH
      - npm install
  build:
    commands:
      - mkdir -p nvd  # Will store nvd here
      - |
        dependency-check.sh \
          --project my-project \
          -s . \
          -f JUNIT \
          --disableNuspec \
          --disableAssembly \
          -d nvd \
          --failOnCVSS $FAIL_ON_CVSS  
      - ls nvd       
# Caching the nvd database so each run doesn't download the
# entire nvd
cache:
  paths:
    - nvd/**/*

reports:
  # ARN of the Codebuild Report created in Cloudformation
  arn:aws:codebuild:us-east-1:111111111111:report-group/OwaspReportGroup-ABC123abc987:
    files:
      - dependency-check-junit.xml
    file-format: JunitXml