version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing completed"
  build:
    commands: 
    - apt-get update
    - apt-get -y install wget
    - apt-get -y install default-jdk
    - wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
    - mkdir zap
    - tar -xvf ZAP_2.12.0_Linux.tar.gz
    - mkdir generated_report
    - ls
    - pwd
    - ls ZAP_2.12.0 
    # - ./ZAP_2.12.0/zap.sh -help
    - mv ./ZAP_2.12.0/zap.sh generated_report
    # - ./ZAP_2.12.0/zap.sh -cmd -full -fullurl http://33f5-2401-4900-1c89-d2ac-1502-8ca-8ea-3ce0.ngrok.io -quickprogress -quickout ../generated_report/zap_report2.html
    # - ./ZAP_2.12.0/zap.sh -cmd -full -fullurl http://example.com
    - ./ZAP_2.12.0/zap.sh -u http://33f5-2401-4900-1c89-d2ac-1502-8ca-8ea-3ce0.ngrok.io -a username=admin@juice-sh.op -a password=admin123 -t
    # - touch dummy.txt
    # - cp dummy.txt generated_report
  post_build:
    commands:
    - ls generated_report
    - ls
    - pwd
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: generated_report